name: kari
description: A new Framework mvc structure project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  reflectable: any
  build_runner: any

  build: '>=0.12.0 <2.0.0'  
  source_gen: ^0.9.0  
  view_reporter:    
    path: lib/core/view/  

dev_dependencies:
  flutter_test:
    sdk: flutter
  view_reporter_generator:
    path: lib/core/view/generator/
flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
